### ISSUE TITLE
Frame dropping interlaced HD content on ATV 4

### ISSUE THREAD

**Issue by anomalousmouse** [zipleen/tvheadend-iphone-client#200] opened 2017-09-24 18:03 UTC
Previously able to watch interlaced HD content on ATV 4 - silky smooth, Bob deinterlacer.  Now visibly dropping frames.  Other platforms (e.g. iPad) no problems.
TVHClient Version: 1.0.2(131)
TVheadend version: 4.2.3-20~g407c8a3 (A19)

Seeing nothing in tvheadend log when frame drops occur - assume it is client.

**Comment by zipleen** [comment] 2017-09-25 10:47
Hi !

I would invite you to come to http://chat.tvhclient.com and discuss this with the users there.
There's some beta testers that are really into this deinterlace stuff, and from what I know they're all ok with it working (we're currently testing new vlckit builds though).

Another thing of note is that version 1.0.2 was released in Feb 8, 2017 - there was no updates since then, so if you did not have issues then and now you have, something in your environment might have changed without you being aware (like the type of stream the channel was transmitting as). 

Also, the iPad / iOS version currently in the app store uses a very old vlckit version - currently I'm beta testing version 3.0 which will update vlckit completely (so both tvOS and iOS versions will have the same vlckit), so right now you can't compare those two.

To make things clear, deinterlace and video playback is actually vlckit (the library that powers VLC), which I have very little control over =) Come and talk in the channel and help out debugging this deinterlace issue and we might figure out a way to reproduce it and open a ticket in VLCKit!

Cheers

**Closed by zipleen** 2017-09-25 10:47 UTC
