### ISSUE TITLE
No EPG with latest Tvheadend Commit

### ISSUE THREAD

**Issue by blablub121** [zipleen/tvheadend-iphone-client#165] opened 2015-10-10 13:06 UTC
Current Appstore release does not fully work with the latest Commit of Tvheadend (HTS Tvheadend 4.1-581~g935f983). Within Tvheadend i get some Logs like: 

2015-10-10 14:53:31.442 http: 192.168.1.1: HTTP/1.1 GET /capabilities -- 404
2015-10-10 14:53:31.444 http: 192.168.1.1: HTTP/1.1 POST /confignames -- 404
2015-10-10 14:53:31.449 http: 192.168.1.1: HTTP/1.1 GET /config -- 404

And within iOS App no EPG is shown, neither on channel overview nor on channel details. It just shows "Not available" or a never ending spinning wheel.

**Comment by zipleen** [comment] 2015-10-10 13:48
Duplicate of #164

This is already fixed in the latest version, waiting for the apple store to review more than a week ago..

**Closed by zipleen** 2015-10-10 13:48 UTC

**Comment by kenji21** [comment] 2015-10-11 07:21
Hi @zipleen,

Are the changes available in tvheadend-ios-lib ?

**Comment by zipleen** [comment] 2015-10-11 08:30
Yes, in https://github.com/zipleen/tvheadend-ios-lib/commit/3cc6736b4129ac273cf7ae674cbbdc723e384e8e

**Comment by kenji21** [comment] 2015-10-11 08:40
:+1:
