### ISSUE TITLE
Feature request: add support for profile selection

### ISSUE THREAD

**Issue by ViGill** [zipleen/tvheadend-iphone-client#160] opened 2015-06-12 16:27 UTC
Hi,

it would be very nice to allow to select the streaming profile.
TVheadend exports the list of profiles that can be used...

With the latest tvheadend, the transcoding parameters are not used.

Thanks!

**Comment by zipleen** [comment] 2015-07-31 11:20
duplicate of #143 =)

I don't think this feature will be here soon, however if you want to transcode you can do a simple workaround: create a user in tvheadend and set the specific profile you want for it. Add it to tvhclient and you'll have the transcoded stream instead of the full one.

**Comment by bjoerns1983** [comment] 2015-08-11 20:45
Hi zipleen,
could you tell me the TVHeadend transcoding parameters which fit the iPhone, or what you would recommend?

**Comment by zipleen** [comment] 2015-08-11 22:22
if you're using tvheadend 4 it should already have created you a profile for iOS.
nevertheless it should be H264 for video and MP4 for sound. Resolution is whatever you can make it work with your machine, normally only SD resolutions can be processed in real time, unless you do some sort of optimisations or you have a awesome cpu (or you can use gpu acceleration)

never try transcoding with a synology =)

**Comment by zipleen** [comment] 2017-09-27 14:22
latest beta supports selecting a stream profile. version 3.0.0 will have this in the server settings

**Closed by zipleen** 2017-09-27 14:22 UTC
