### ISSUE TITLE
iOS AutoRec feature request

### ISSUE THREAD

**Issue by jecdk** [zipleen/tvheadend-iphone-client#250] opened 2019-07-29 12:10 UTC
Requesting the possibility when editing AutoRecordings to specify weekdays.
It is long awaited (#97)  and would really lift the AutoRec functionality to a higher levels of usefulness.

**Comment by zipleen** [comment] 2019-07-29 12:39
yeah no need to add another ticket, this is a duplicate of #97 

almost everything is missing in the autorec screen... but I never finished it... too boring :D

**Closed by zipleen** 2019-07-29 12:39 UTC
