### ISSUE TITLE
Stream Profile selection and H265 pre defined option.

### ISSUE THREAD

**Issue by turfrider** [zipleen/tvheadend-iphone-client#192] opened 2016-12-27 17:50 UTC
Currently we need to select the video codec settings within the app. I would like to be able to use my defined profiles on the tvh server, this allows me to do all configuration centrally. 

The current ability to select codecs from within the app is useful, please include h265 as well.

**Comment by zipleen** [comment] 2017-02-09 12:25
Selecting the codec is only for a really old transcoding option of version 3.6

Selecting profiles is a future feature. This is duplicate of #160 

if you want to transcode you can do a simple workaround: create a user in tvheadend and set the specific profile you want for it. Add it to tvhclient and you'll have the transcoded stream instead of the full one.

**Closed by zipleen** 2017-02-09 12:25 UTC
