### ISSUE TITLE
Icons 404

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [zipleen/tvheadend-iphone-client#166] opened 2015-10-21 16:43 UTC
Hey,
i'm running few days old tvh build. on another webserver are the picons.

i'm using only path option an then reference names.
kodi shows them correctly, also tvh backend. 

only your app can't load them.
in log i see 404, but if i copy this url an open in safari png is shown correctly...

**Comment by zipleen** [comment] 2015-10-24 10:53
Hi, I can confirm this.
I haven't noticed it because if the images are cached they still show up.

I'll look into it!

If you want I can add you to the beta testers so you can test the fix once it's released. Send me an email to tvhclient at gmail and I'll send you the invite to that email

**Comment by c-o-m-m-a-n-d-e-r** [comment] 2015-10-24 10:57
you got mail

**Comment by c-o-m-m-a-n-d-e-r** [comment] 2016-04-19 11:16
any news here?

**Comment by zipleen** [comment] 2016-04-19 11:21
actually I don't remember this at all lol
isn't this fixed in the current beta iOS version ?

**Comment by c-o-m-m-a-n-d-e-r** [comment] 2016-04-19 11:22
hehe i totally forgot this too ...
can you resend me beta? can't see in testflight anymore.

christian # brauwers DOT com

**Comment by zipleen** [comment] 2016-04-19 11:26
done

**Closed** 2017-08-17 23:43 UTC
Labels: bug
